version: '3'

services:
    filecloud.mongodb:
        container_name: 'filecloud.mongodb'
        image: mongodb/mongodb-community-server:4.4-ubuntu2004
        environment:
            - mongodb_data_container=/data/db
        volumes:
            - mongo_database:/data/db
        restart: unless-stopped

    filecloud.server:
        container_name: 'filecloud.server'
        image: filecloud/filecloudserver23.1:latest
        depends_on:
            - filecloud.mongodb
            - filecloud.preview
        volumes:
            - cloud_data:/var/clouddata
            - var_html:/var/www/html
        restart: unless-stopped
        links:
            - filecloud.mongodb
        ports:
            - "8083:80"
            - "8084:443"

    filecloud.preview:
        container_name: 'filecloud.preview'
        image: filecloud/filecloudpreview22.1:latest
        volumes:
            - cloud_data:/var/clouddata
            - var_html:/var/www/html
            - /mnt/filecloud:/mnt/filecloud
        restart: unless-stopped

    filecloud.solr:
        container_name: 'filecloud.solr'
        image: filecloud/filecloudsolr21.3:latest
        volumes:
            - solr_data:/var/solr
            - var_html:/var/www/html
            - /mnt/filecloud:/mnt/filecloud

volumes:
    mongo_database:
    cloud_data:
    solr_data:
    var_html: